### ISSUE TITLE
Replace Google Analytics Dashboard dependency

### ISSUE THREAD

**Issue by jtsternberg** [jtsternberg/Google-Analytics-Top-Content-Widget#1]
Our plugin is currently broken because the plugin is using a deprecated oAuth method. See: https://github.com/Yoast/google-analytics-dashboard/issues/13

**Comment by erikberger** [comment]
Hi Justin.  Any chance you would switch dependencies to the Google Analytics for Wordpress plugin that Yoast seems to be supporting instead?  https://github.com/Yoast/google-analytics-dashboard/issues/13#issuecomment-101949753  .

**Comment by jtsternberg** [comment]
@erikberger there is a chance, but either way, it's going to require finding some time that I don't really have right now. It's definitely on my radar.
