### ISSUE TITLE
Retrieve data only?

### ISSUE THREAD

**Issue by pbowyer** [jtsternberg/Google-Analytics-Top-Content-Widget#10]
Hello, this looks an excellent plugin and a great improvement over hitting the server to record each page view.

For my needs I don't need a widget, and I have been looking through the code trying to work out - is it possible to get the data directly rather than rendered in HTML? I think not, but before I did anything I thought I'd check I've not missed something, and if you'd be interested in having this added?

**Comment by jtsternberg** [comment]
This is completely untested, but it's possible to do it in a bit of hacky way like so:

``` php

class GA_Top_Content_Items {

    protected $all_items = array();

    public function collect_items( $list_item, $google_result, $post, $counter, $title, $url ) {
        $this->all_items[ $google_result ] = compact( 'post', 'list_item', 'counter', 'title', 'url' );
    }

    function get_ga_top_content_items( $atts = array() ) {
        if ( ! class_exists( 'GA_Top_Content' ) ) {
            return false;
        }


        add_filter( 'gtc_list_item', array( $this, 'collect_items' ), 99, 6 );
        GA_Top_Content::get_instance()->top_content_shortcode( $atts );
        remove_filter( 'gtc_list_item', array( $this, 'collect_items' ), 99, 6 );

        return $this->all_items;
    }
}

function get_ga_top_content_items( $atts = array() ) {
    $ga = new GA_Top_Content_Items();
    return $ga->get_ga_top_content_items( $atts );
}
```

And you would use the `get_ga_top_content_items( $atts )` function, and pass it any of the parameters/attributes that you would via the shortcode.
