### ISSUE TITLE
Widget not filtering out "home/frontpage"

### ISSUE THREAD

**Issue by cspicuzza** [jtsternberg/Google-Analytics-Top-Content-Widget#11]
Since two upgrades ago, the home/frontpage has been showing up in our widget despite having the option enabled.  You can see the "Top Stories" widget here: http://www.theprp.com/

Thanks!

**Comment by jtsternberg** [comment]
Are you still seeing this issue?

**Comment by cspicuzza** [comment]
The issue has been resolved.   I haven't tested it yet with the latest GA Monsterinsights update
