### ISSUE TITLE
`google_analytics_views` start_date arg

### ISSUE THREAD

**Issue by entr** [jtsternberg/Google-Analytics-Top-Content-Widget#16]
Any particular reason why not pass `$post->post_date` as `start_date` in `google_analytics_views` shortcode? I don't know how useful is to show views count for only the last 30 days.

Any thoughts?

**Comment by jtsternberg** [comment]
That is something you can override with the shortcode parameters if you prefer. Showing the last 30 days of views makes perfect sense from an analytics standpoint. Setting `$post->post_date` as the default is quite arbitrary, and most would not appreciate this change.

**Comment by entr** [comment]
Got it. Any chance for getting a template tag to use directly in templates instead of relying on shortcodes?

**Comment by jtsternberg** [comment]
You can create your own template tag (or use the method directly) like so:

``` php
function ga_top_content_views_shortcode( $args = array(), $content = '' ) {
    return class_exists( 'GA_Top_Content' )
        ? GA_Top_Content::get_instance()->views_shortcode( $args, $content )
        : new WP_Error( 'missing_gatc', 'Please install/activate the "Google Analytics Top Content Widget" plugin.' );
}
```

**Comment by entr** [comment]
I will most likely create one but will you consider a pull request?

**Comment by jtsternberg** [comment]
Even if I add template tags to the plugin, you'd still need to use `function_exists` checks to insure your site doesn't implode if the plugin gets deactivated, so your code would not be much different:

``` php
<?php if ( function_exists( 'ga_top_content_views_shortcode' ) ) : ?>
    <?php ga_top_content_views_shortcode( $args, $content ); ?>
<?php endif; ?>
```

If you prefer not to use the helper function I provided, you can do the same thing now:

``` php
<?php if ( class_exists( 'GA_Top_Content' ) ) : ?>
    <?php GA_Top_Content::get_instance()->views_shortcode( $args, $content ); ?>
<?php endif; ?>
```

**Comment by entr** [comment]
Sorry, didn't realize at first you provided a complete example. Thanks, those will do just fine.
