### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by chriscct7** [jtsternberg/Google-Analytics-Top-Content-Widget#19]
Just as a heads up, the repo description says to use the Google Analytics Dashboard plugin, which is a plugin Yoast abandoned instead of GA by MI:
![image](https://cloud.githubusercontent.com/assets/1324637/20039317/cf3a2c88-a40f-11e6-94d0-8e0d05029a02.png)

**Comment by jtsternberg** [comment]
Fixed, thank you!
